---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: coroot-license
  namespace: coroot
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: coroot-license
    creationPolicy: Owner
  data:
    - secretKey: license-key
      remoteRef:
        key: coroot
        property: license-key
