---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: arc-github-pat
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: arc-github-pat
    creationPolicy: Owner
  data:
    - secretKey: github_token
      remoteRef:
        key: arc-github-pat
        property: token
