---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: node-hp-scan-to-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: node-hp-scan-to-secrets
    creationPolicy: Owner
  data:
    - secretKey: PAPERLESS_TOKEN
      remoteRef:
        key: paperless-ngx-api
        property: token
