---
apiVersion: coroot.com/v1
kind: Coroot
metadata:
  name: coroot
spec:
  enterpriseEdition:
    licenseKeySecret:
      name: coroot-license
      key: license-key
  storage:
    size: 10Gi
    className: longhorn
  prometheus:
    retention: 2d
    storage:
      size: 10Gi
      className: longhorn
  clickhouse:
    shards: 1
    replicas: 1
    storage:
      size: 10Gi
      className: longhorn
  nodeAgent:
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
      limits:
        cpu: 500m
        memory: 1Gi
  clusterAgent: {}
