---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vertical-pod-autoscaler
spec:
  chart:
    spec:
      chart: vpa
      version: 4.x
      sourceRef:
        kind: HelmRepository
        name: fairwinds-stable
  interval: 1h
  values:
    recommender:
      enabled: true
      extraArgs:
        pod-recommendation-min-cpu-millicores: "5"
        pod-recommendation-min-memory-mb: "16"
      resources:
        requests:
          cpu: 50m
          memory: 256Mi
        limits:
          memory: 512Mi
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities: { drop: ["ALL"] }
    updater:
      enabled: false
    admissionController:
      enabled: false
