---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-ngx
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: paperless-ngx-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        PAPERLESS_SECRET_KEY: "{{ .secret_key }}"
        PAPERLESS_ADMIN_PASSWORD: "{{ .admin_password }}"
        PAPERLESS_REDIS: "redis://:{{ .redis_password }}@paperless-ngx-redis-master.default.svc.cluster.local:6379"
  data:
    - secretKey: secret_key
      remoteRef:
        key: paperless-ngx
        property: secret_key
    - secretKey: admin_password
      remoteRef:
        key: paperless-ngx
        property: admin_password
    - secretKey: redis_password
      remoteRef:
        key: paperless-ngx
        property: redis_password
