---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ./ocirepository.yaml
  - ./helmrepository.yaml
  - ./postgres-cluster.yaml
  - ./postgres-externalsecret.yaml
  - ./externalsecret.yaml
  - ./redis-externalsecret.yaml
  - ./redis-helmrelease.yaml
  - ./helmrelease.yaml
