---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cobalt
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: cobalt-keys
    template:
      engineVersion: v2
      data:
        keys.json: "{{ .keysJson }}"
  data:
    - secretKey: keysJson
      remoteRef:
        key: cobalt
        property: keys_json
