---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: truenas-exporters
  namespace: flux-system
spec:
  dependsOn:
    - name: vmsingle
  interval: 1h
  path: ./kubernetes/apps/monitoring/truenas-exporters/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: monitoring
  wait: false
