---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-ngx-postgres-superuser
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: paperless-ngx-postgres-superuser
    template:
      engineVersion: v2
      data:
        username: paperless
        password: "{{ .password }}"
  dataFrom:
    - extract:
        key: paperless-ngx-postgres
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-ngx-postgres-app
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: paperless-ngx-postgres-app
    template:
      engineVersion: v2
      data:
        username: paperless
        password: "{{ .password }}"
        uri: "postgresql://paperless:{{ .password }}@paperless-ngx-postgres-rw.default.svc.cluster.local:5432/paperless"
  dataFrom:
    - extract:
        key: paperless-ngx-postgres
