---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-ngx-redis
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: paperless-ngx-redis-auth
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        password: "{{ .redis_password }}"
  data:
    - secretKey: redis_password
      remoteRef:
        key: paperless-ngx
        property: redis_password
